config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :registered_applications do
    resources :events
  end
  root to:"welcome#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @event}
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @events = Event.all
  end

  def show
    @event = Event.all

    @events = @event.events.group_by(&:name)
  end

  def update
  respond_to do |format|
    if @event.update(recipe_params)
      format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      format.json { render :show, status: :ok, location: @recipe }
    else
      format.html { render :edit }
      format.json { render json: @event.errors, status: :unprocessable_entity }
    end
  end
end

  def destroy
    @event.destroy
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = RegisteredApplication.new(registered_application_params)

    respond_to do |format|
      if @registered_application.save
        format.html { redirect_to @registered_application, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @registered_application}
      else
        format.html { render :new }
        format.json { render json: @registered_application.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @registered_applications = RegisteredApplication.all
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])

    @events = @registered_application.events.group_by(&:name)
  end

  def update
  respond_to do |format|
    if @registered_application.update(recipe_params)
      format.html { redirect_to @registered_application, notice: 'Application was successfully updated.' }
      format.json { render :show, status: :ok, location: @recipe }
    else
      format.html { render :edit }
      format.json { render json: @registered_application.errors, status: :unprocessable_entity }
    end
  end
end

  def destroy
    @registered_application.destroy
  end

  private
    def registered_application_params
      params.require(:registered_application).permit(:name, :url)
    end

    def registered_application_params
        params.require(:registered_application).permit(:name, :url)
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for[@registered_application,@event] do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
<% end %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Registered Applications</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @events.present? %>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= link_to 'Show', registered_application_events_path %></td>
          <td><%#= link_to 'Edit', edit_event_path(event) %></td>
          <td><%#= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New registered application', new_registered_application_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', new_registered_application_event_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>URL:</strong>
  <% @event.each do |app| %>
    <%= app.url %>
  <% end %>
</p>

<p>

<p>
<%= link_to 'Edit', edit_registered_application_event_path(@event) %> |
<%= link_to 'Back', registered_application_event_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="widtth=devise-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Registered Application", registered_applications_path %></li>
      <% if current_user %>
    <li><%= current_user.email %></li>
    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
    <li><%= link_to "Sign In", new_user_session_path %></li>
  <% end %>
    </ul>

  <%= yield %>
</div>

</body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for(@registered_application) do |f| %>
  <% if @registered_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registered_application.errors.count, "error") %> prohibited this registered_application from being saved:</h2>

      <ul>
      <% @registered_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registered_applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Registered Applications</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>URL</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @registered_applications.present? %>
      <% @registered_applications.each do |registered_application| %>
        <tr>
          <td><%= registered_application.name %></td>
          <td><%= registered_application.url %></td>
          <td><%= link_to 'Show', registered_application %></td>
          <td><%#= link_to 'Edit', edit_registered_application_path(registered_application) %></td>
          <td><%#= link_to 'Destroy', registered_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New registered application', new_registered_application_path %>

app/views/registered_applications/new.html.erb
<h1>New Registered Application</h1>

<%= render 'form' %>

<%= link_to 'Back', registered_application_path %>

app/views/registered_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @registered_application.name %>
</p>

<p>
  <strong>URL:</strong>
  <% @registered_application.url %>
</p>

<p>
  <strong>Event:</strong>
  <% @registered_application.events.each do |event| %>
  <br/>
    <%= event.name %>
  <% end %>
</p>
<p>
<%= link_to 'Events', registered_application_events_path(1) %> |
<%= link_to 'Edit', edit_registered_application_path(@registered_application) %> |
<%= link_to 'Back', registered_application_path %>
</p>

app/views/welcome/index.html.erb
<h1><%= 'Welcome to Blocmetrics,' %></h1>
<h1><%= current_user.email %></h1>